# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
#download NuGet packages and project-specific tools
- task: DotnetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'

# build the project 

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs: 
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'

# run unit test 
- task: DotnetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'

# publish artifacts

- task: DotnetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishwebprojects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildconfiguration)'

#upload build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'publish artifact: drop'
  inputs:
    ArtifactName: 'AzureDemoPipeLine'
